package giaodien.CustomClass;
import giaodien.Login;
import java.awt.Color;
import java.sql.SQLException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import javax.swing.JOptionPane;

import connectDB.ConnectDB;
import dao.TaiKhoanDao;
import entity.TaiKhoan;

public class ChangePassword extends javax.swing.JFrame {


    public ChangePassword() throws SQLException{
        initComponents();
        ConnectDB.getInstance().getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Right = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Left = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTenDangNhap = new giaodien.CustomClass.TextField();
        btnDoiMatKhau = new giaodien.CustomClass.Button();
        txtMatKhauMoi1 = new giaodien.CustomClass.PasswordField();
        txtMatKhauCu = new giaodien.CustomClass.PasswordField();
        txtMatKhauMoi2 = new giaodien.CustomClass.PasswordField();
        button2 = new giaodien.CustomClass.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ChangePassword");
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        Right.setBackground(new java.awt.Color(255, 255, 255));
        Right.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgLogin/tien-sanh-khach-san.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(800, 600));
        jLabel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jLabel1.setPreferredSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout RightLayout = new javax.swing.GroupLayout(Right);
        Right.setLayout(RightLayout);
        RightLayout.setHorizontalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, Short.MAX_VALUE)
        );
        RightLayout.setVerticalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(Right);
        Right.setBounds(0, 0, 400, 500);

        Left.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(23, 195, 178));
        jLabel2.setText("ĐỔI MẬT KHẨU");

        jLabel6.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        jLabel6.setText("StaRail Hotel  Management");

        txtTenDangNhap.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtTenDangNhap.setLabelText("Tên đăng nhập");
        txtTenDangNhap.setLineColor(new java.awt.Color(23, 195, 178));
        txtTenDangNhap.setPreferredSize(new java.awt.Dimension(64, 50));

        btnDoiMatKhau.setBackground(new java.awt.Color(23, 195, 178));
        btnDoiMatKhau.setBorder(null);
        btnDoiMatKhau.setText("THAY ĐỔI");
        btnDoiMatKhau.setBorderColor(new java.awt.Color(23, 195, 178));
        btnDoiMatKhau.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnDoiMatKhau.setPreferredSize(new java.awt.Dimension(125, 35));
        btnDoiMatKhau.setRadius(20);
        btnDoiMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDoiMatKhauMouseExited(evt);
            }
        });
        btnDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiMatKhauActionPerformed(evt);
            }
        });

        txtMatKhauMoi1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtMatKhauMoi1.setLabelText("Mật khẩu mới");
        txtMatKhauMoi1.setLineColor(new java.awt.Color(23, 195, 178));
        txtMatKhauMoi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatKhauMoi1ActionPerformed(evt);
            }
        });

        txtMatKhauCu.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtMatKhauCu.setLabelText("Mật khẩu cũ");
        txtMatKhauCu.setLineColor(new java.awt.Color(23, 195, 178));

        txtMatKhauMoi2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtMatKhauMoi2.setLabelText("Mật khẩu mới");
        txtMatKhauMoi2.setLineColor(new java.awt.Color(23, 195, 178));

        button2.setBorder(null);
        button2.setText("Quay lại");
        button2.setBorderColor(java.awt.Color.white);
        button2.setColor(new java.awt.Color(254, 249, 239));
        button2.setRadius(15);
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LeftLayout = new javax.swing.GroupLayout(Left);
        Left.setLayout(LeftLayout);
        LeftLayout.setHorizontalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftLayout.createSequentialGroup()
                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(LeftLayout.createSequentialGroup()
                            .addGap(85, 85, 85)
                            .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtMatKhauMoi1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                .addComponent(txtTenDangNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                .addComponent(txtMatKhauCu, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                .addComponent(txtMatKhauMoi2, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                .addComponent(btnDoiMatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(LeftLayout.createSequentialGroup()
                                    .addGap(46, 46, 46)
                                    .addComponent(jLabel2))))
                        .addGroup(LeftLayout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addComponent(jLabel6))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        LeftLayout.setVerticalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(txtMatKhauCu, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(txtMatKhauMoi1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(txtMatKhauMoi2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDoiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );

        jPanel1.add(Left);
        Left.setBounds(400, 0, 400, 500);
        Left.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoiMatKhauMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoiMatKhauMouseExited
        btnDoiMatKhau.setBackground(new Color(23,195,178));
    }//GEN-LAST:event_btnDoiMatKhauMouseExited

    private void txtMatKhauMoi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatKhauMoi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatKhauMoi1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        try {
            Login LoginFrame = new Login();
            LoginFrame.setVisible(true);
            LoginFrame.pack();
            LoginFrame.setLocationRelativeTo(null); // center
            this.dispose();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_button2ActionPerformed
    
	private boolean regMatKhau(String matKhau) {
		String regex = "^(?=.*[A-Z])(?=.*\\d).{8,}$";

		Pattern pattern = Pattern.compile(regex);
		Matcher matcher = pattern.matcher(matKhau);

		return matcher.matches();
	}

    private void btnDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiMatKhauActionPerformed
        String tenDangNhap = txtTenDangNhap.getText();
        char[] matKhauCu = txtMatKhauCu.getPassword();
        char[] matKhauMoi1 = txtMatKhauMoi1.getPassword();
        char[] matKhauMoi2 = txtMatKhauMoi2.getPassword();
        String mkCu = String.valueOf(matKhauCu);
        String mkMoi1 = String.valueOf(matKhauMoi1);
        String mkMoi2 = String.valueOf(matKhauMoi2);
        TaiKhoanDao tkDao = new TaiKhoanDao();
        TaiKhoan taiKhoan = tkDao.timTaiKhoanTheoTenDangNhap(tenDangNhap);
		if (tenDangNhap.equals("") || mkCu.equals("") || mkMoi1.equals("") || mkMoi2.equals("")) {
			JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin");
		} else {
			if (taiKhoan == null) {
				JOptionPane.showMessageDialog(null, "Tên đăng nhập không tồn tại");
			} else {
				if (!taiKhoan.getMatKhau().equals(mkCu)) {
					JOptionPane.showMessageDialog(null, "Mật khẩu cũ không đúng");
				} if (mkCu.equals(mkMoi1)) {
					JOptionPane.showMessageDialog(null, "Mật khẩu bị trùng với cái cũ, đổi lại đi");
				}else {
					if (!mkMoi1.equals(mkMoi2)) {
						JOptionPane.showMessageDialog(null, "Mật khẩu mới không trùng khớp");
					} if (regMatKhau(mkMoi1) == false) {
						JOptionPane.showMessageDialog(null, "Mật khẩu mới phải có ít nhất 8 ký tự, bao gồm 1 chữ hoa và 1 số");
					}
					else {
						taiKhoan.setMatKhau(mkMoi1);
						tkDao.suaTaiKhoan(taiKhoan);
						JOptionPane.showMessageDialog(null, "Đổi mật khẩu thành công");
					}
				}
			}
		}
    }//GEN-LAST:event_btnDoiMatKhauActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Left;
    private javax.swing.JPanel Right;
    private giaodien.CustomClass.Button btnDoiMatKhau;
    private giaodien.CustomClass.Button button2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private giaodien.CustomClass.PasswordField txtMatKhauCu;
    private giaodien.CustomClass.PasswordField txtMatKhauMoi1;
    private giaodien.CustomClass.PasswordField txtMatKhauMoi2;
    private giaodien.CustomClass.TextField txtTenDangNhap;
    // End of variables declaration//GEN-END:variables
    
    public static void main(String[] args) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					new ChangePassword().setVisible(true);
				} catch (SQLException e) {
					e.printStackTrace();
				}
			}
		});
	}
}
