
package giaodien;

import dao.ChucVuDao;
import dao.DichVuDao;
import dao.HangThanhVienDao;
import dao.KhachHangDao;
import dao.NhanVienDao;

import static java.awt.Color.red;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

import giaodien.CustomClass.DateChooser;
import connectDB.ConnectDB;
import dao.PhongDao;
import dao.TaiKhoanDao;
import dao.HoaDonDao;
import entity.HoaDon;
import entity.ChucVu;
import entity.DichVu;
import entity.HangThanhVien;
import entity.KhachHang;
import entity.NhanVien;
import entity.Phong;

import java.text.ParseException;
import java.time.LocalDateTime;
import java.util.stream.Collectors;

import javax.swing.JFrame;
import menu.MenuEvent;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableRowSorter;
public class DanhSachHoaDon_Gui1 extends javax.swing.JPanel {

    /**
     * Creates new form DanhSachHoaDon_Gui1
     */
    public DanhSachHoaDon_Gui1() {
        initComponents();
         txtNgayLapHoaDon.setText(null);
         loadDanhSachHoaDon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateNgayLapHoaDon = new giaodien.CustomClass.DateChooser();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DanhSachHoaDon = new javax.swing.JTable();
        txtHoTen = new giaodien.CustomClass.TextFieldShadow();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNgayLapHoaDon = new giaodien.CustomClass.TextFieldShadow();
        btnTimKiem = new giaodien.CustomClass.Button();
        btnNgayLapHoaDon = new giaodien.CustomClass.Button();
        btnSapXep = new giaodien.CustomClass.Button();

        setPreferredSize(new java.awt.Dimension(1520, 790));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        DanhSachHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã hóa đơn", "Tên khách hàng", "Ngày lập", "Tổng tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        DanhSachHoaDon.setRowHeight(40);
        jScrollPane1.setViewportView(DanhSachHoaDon);

        txtHoTen.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("Họ tên");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Ngày lập");

        txtNgayLapHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnNgayLapHoaDon.setBorder(null);
        btnNgayLapHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgLogin/calendar.png"))); // NOI18N
        btnNgayLapHoaDon.setBorderColor(new java.awt.Color(255, 255, 255));
        btnNgayLapHoaDon.setColorOver(new java.awt.Color(204, 204, 204));
        btnNgayLapHoaDon.setRadius(20);
        btnNgayLapHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNgayLapHoaDonActionPerformed(evt);
            }
        });

        btnSapXep.setText("Sắp xếp");
        btnSapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSapXepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel2)
                        .addGap(30, 30, 30)
                        .addComponent(txtNgayLapHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNgayLapHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112)
                        .addComponent(btnSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnNgayLapHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(54, 54, 54)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(txtNgayLapHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1290, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loadDanhSachHoaDon() {
    try {
        // Gọi hàm timDanhSachHoaDon từ HoaDonDao để lấy danh sách hóa đơn
        HoaDonDao hoaDonDao = new HoaDonDao();
        List<Object[]> danhSachHoaDon = hoaDonDao.timDanhSachHoaDon();

        // Tạo DefaultTableModel để cập nhật dữ liệu lên bảng DanhSachHoaDon
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("STT");
        model.addColumn("Mã hóa đơn");
        model.addColumn("Tên khách hàng");
        model.addColumn("Ngày lập");
        model.addColumn("Tổng tiền");

        // Duyệt qua danh sách hóa đơn và cập nhật dữ liệu vào model
        int stt = 1;
        for (Object[] hoaDonInfo : danhSachHoaDon) {
            // Định dạng lại ngày từ LocalDateTime thành chuỗi "yyyy-MM-dd"
            LocalDateTime ngayLap = (LocalDateTime) hoaDonInfo[2];
            String formattedNgayLap = ngayLap.format(DateTimeFormatter.ofPattern("dd-MM-yyyy"));

            model.addRow(new Object[]{stt, hoaDonInfo[0], hoaDonInfo[1], formattedNgayLap, hoaDonInfo[3]});
            stt++;
        }

        // Đặt model cho bảng DanhSachHoaDon
        DanhSachHoaDon.setModel(model);

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi khi tìm kiếm danh sách hóa đơn.", "Lỗi", JOptionPane.ERROR_MESSAGE);
    }
}
    private DefaultTableModel originalTableModel;
    private int sortState = 0; 
    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        loadDanhSachHoaDon();
        // Lấy dữ liệu từ ô nhập liệu
        String tenKhachHang = txtHoTen.getText().trim().toLowerCase(); // Chuyển tên khách hàng về chữ thường
        String ngayNhapVao = txtNgayLapHoaDon.getText().trim();

        // Chuyển định dạng ngày tháng nhập vào về định dạng chuẩn "yyyy-MM-dd"

        // Tạo một list để lưu các hàng cần hiển thị sau khi tìm kiếm
        List<Object[]> rowsToShow = new ArrayList<>();

        // Lấy model của bảng
        DefaultTableModel model = (DefaultTableModel) DanhSachHoaDon.getModel();

        // Duyệt qua từng hàng trong bảng
        for (int i = 0; i < model.getRowCount(); i++) {
            // Lấy dữ liệu của hàng thứ i
            Object[] rowData = model.getDataVector().get(i).toArray();

            // Chuyển dữ liệu tên khách hàng trong bảng về chữ thường
            String tenKhachHangTrongBang = ((String) rowData[2]).toLowerCase();

            // Chuyển định dạng ngày tháng trong bảng về định dạng chuẩn "yyyy-MM-dd"
            String ngayLapTrongBang = (String) rowData[3];

            // Kiểm tra điều kiện tìm kiếm
            boolean matchTenKhachHang = tenKhachHang.isEmpty() || tenKhachHangTrongBang.contains(tenKhachHang); // So sánh tên khách hàng với tên nhập vào
            boolean matchNgayLap = ngayNhapVao == null || ngayLapTrongBang.equals(ngayNhapVao); // So sánh ngày lập với ngày nhập vào

            // Điều kiện tìm kiếm
            boolean addRow = false;
            if (!tenKhachHang.isEmpty() && ngayNhapVao.isEmpty()) {
                // Tìm kiếm theo tên khách hàng
                addRow = matchTenKhachHang;
            } else if (tenKhachHang.isEmpty() && !ngayNhapVao.isEmpty()) {
                // Tìm kiếm theo ngày lập
                addRow = matchNgayLap;
            } else if (!tenKhachHang.isEmpty() && !ngayNhapVao.isEmpty()) {
                // Tìm kiếm theo cả hai
                addRow = matchTenKhachHang && matchNgayLap;
            }

            // Thêm hàng nếu điều kiện tìm kiếm thỏa mãn
            if (addRow) {
                rowsToShow.add(rowData);
            }
        }

        // Xóa tất cả các hàng hiện có trong bảng
        model.setRowCount(0);

        // Thêm các hàng đã tìm được vào bảng
        for (Object[] row : rowsToShow) {
            model.addRow(row);
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnNgayLapHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNgayLapHoaDonActionPerformed
        dateNgayLapHoaDon.showPopup();
    }//GEN-LAST:event_btnNgayLapHoaDonActionPerformed
    
    private void btnSapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSapXepActionPerformed
        DefaultTableModel model = (DefaultTableModel) DanhSachHoaDon.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        DanhSachHoaDon.setRowSorter(sorter);
        sorter.setSortable(4, true); // Cột số 5 (index 4) của bảng

        // Xác định hướng sắp xếp dựa trên trạng thái hiện tại
        SortOrder sortOrder = (sortState % 2 == 0) ? SortOrder.ASCENDING : SortOrder.DESCENDING;

        // Thiết lập trình sắp xếp
        List<RowSorter.SortKey> sortKeys = new ArrayList<>();
        sortKeys.add(new RowSorter.SortKey(4, sortOrder));
        sorter.setSortKeys(sortKeys);

        // Duyệt qua tất cả các hàng và sắp xếp chúng
        List<RowSorter.SortKey> keys = new ArrayList<>();
        keys.add(new RowSorter.SortKey(4, sortOrder));
        sorter.setSortKeys(keys);

        // Sắp xếp lại toàn bộ dữ liệu
        sorter.sort();

        // Cập nhật trạng thái sắp xếp
        sortState++;
    }//GEN-LAST:event_btnSapXepActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DanhSachHoaDon;
    private giaodien.CustomClass.Button btnNgayLapHoaDon;
    private giaodien.CustomClass.Button btnSapXep;
    private giaodien.CustomClass.Button btnTimKiem;
    private giaodien.CustomClass.DateChooser dateNgayLapHoaDon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private giaodien.CustomClass.TextFieldShadow txtHoTen;
    private giaodien.CustomClass.TextFieldShadow txtNgayLapHoaDon;
    // End of variables declaration//GEN-END:variables
}
