/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package giaodien;

import gui.*;
import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import table.TableActionCellEditor;
import table.TableActionCellRender;
import table.TableActionEvent;


/**
 *
 * @author Huynguyen
 */
public class DichVu extends javax.swing.JFrame {

    /**
     * Creates new form DichVu
     */
    public DichVu() {
        
        setUndecorated(true);
        setAlwaysOnTop(true);
        setResizable(false);
        Toolkit tk = Toolkit.getDefaultToolkit();
        int x=(int) tk.getScreenSize().getWidth();
        int y=(int) tk.getScreenSize().getHeight();
        setSize(x, y);
        initComponents();
        TableActionEvent event = new TableActionEvent() {
                        @Override
            public void onEdit(int row) {
                System.out.println("Edit row: "+row);
            }

            @Override
        public void onDelete(int row) {
            if(tableDV.isEditing()){
                tableDV.getCellEditor().stopCellEditing();
            }

            DefaultTableModel model = (DefaultTableModel) tableDV.getModel();
            model.removeRow(row);

            // Cập nhật lại số thứ tự
            updateSerialNumbers();

            // Tính toán lại tổng giá tiền và cập nhật lên textField giaDV
            calculateTotalPrice();
        }

        // Phương thức cập nhật lại số thứ tự
        private void updateSerialNumbers() {
            int dem=0;
            for (int i = 0; i < tableDV.getRowCount(); i++) {
                tableDV.setValueAt(i + 1, i, 0); // Cập nhật số thứ tự vào cột 0 (stt)
                dem=i;
            }
            counter=dem+2;
        }


            @Override
            public void onView(int row) {
                System.out.println("Viewt row: "+row);
            }
        };
        tableDV.getColumnModel().getColumn(5).setCellRenderer(new TableActionCellRender());
        tableDV.getColumnModel().getColumn(5).setCellEditor(new TableActionCellEditor(event));
        // Tạo một renderer cho tiêu đề của bảng
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(new Color(34, 124, 157)); // Thay đổi màu sắc của hàng tiêu đề 
        headerRenderer.setForeground(Color.WHITE); // Thiết lập màu chữ cho hàng tiêu đề

        // Lấy header của bảng và thiết lập renderer cho từng cột
        JTableHeader tableHeader = tableDV.getTableHeader();
        for (int i = 0; i < tableDV.getColumnCount(); i++) {
            tableHeader.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
        headerRenderer.setBackground(new Color(34, 124, 157)); // Thay đổi màu sắc của hàng tiêu đề 
        headerRenderer.setForeground(Color.WHITE); // Thiết lập màu chữ cho hàng tiêu đề

        // Lấy header của bảng và thiết lập renderer cho từng cột
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        scrollPaneWin111 = new ScollBar1.ScrollPaneWin11();
        panelRound1 = new giaodien.PanelRound();
        panelRound2 = new giaodien.PanelRound();
        jLabel3 = new javax.swing.JLabel();
        buttonRuou = new giaodien.Button();
        jLabelRuou = new javax.swing.JLabel();
        panelRound3 = new giaodien.PanelRound();
        jLabel5 = new javax.swing.JLabel();
        buttonBuaAn = new giaodien.Button();
        jLabelBuaAn = new javax.swing.JLabel();
        panelRound4 = new giaodien.PanelRound();
        jLabel7 = new javax.swing.JLabel();
        buttonBaoThuc = new giaodien.Button();
        jLabelBaoThuc = new javax.swing.JLabel();
        panelRound5 = new giaodien.PanelRound();
        jLabel9 = new javax.swing.JLabel();
        buttonKeThem = new giaodien.Button();
        jLabelKeThem = new javax.swing.JLabel();
        panelRound6 = new giaodien.PanelRound();
        jLabel11 = new javax.swing.JLabel();
        buttonGiatLa = new giaodien.Button();
        jLabelGiatLa = new javax.swing.JLabel();
        panelRound7 = new giaodien.PanelRound();
        jLabel13 = new javax.swing.JLabel();
        buttonDuaDon = new giaodien.Button();
        jLabelDuaDon = new javax.swing.JLabel();
        jScrollPane1 = new ScollBar1.ScrollPaneWin11();
        tableDV = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        textFieldShadow1 = new giaodien.TextFieldShadow();
        button7 = new giaodien.Button();
        button1 = new giaodien.Button();
        giaDV = new giaodien.TextFieldShadow();
        menu1 = new menu.Menu();
        header1 = new component.Header();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(1297, 783));

        jButton1.setText("jButton1");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("Danh sách dịch vụ");

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        panelRound2.setBackground(new java.awt.Color(254, 249, 239));
        panelRound2.setPreferredSize(new java.awt.Dimension(300, 200));
        panelRound2.setRoundBottomLeft(20);
        panelRound2.setRoundBottomRight(20);
        panelRound2.setRoundTopLeft(20);
        panelRound2.setRoundTopRight(20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgLogin/ruou.jpg"))); // NOI18N

        buttonRuou.setText("Rượn vang");
        buttonRuou.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonRuou.setRadius(20);
        buttonRuou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRuouActionPerformed(evt);
            }
        });

        jLabelRuou.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabelRuou.setText("3.300.000 VND");

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonRuou, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabelRuou)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelRuou)
                .addGap(0, 10, Short.MAX_VALUE))
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(buttonRuou, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRound3.setBackground(new java.awt.Color(254, 249, 239));
        panelRound3.setPreferredSize(new java.awt.Dimension(300, 200));
        panelRound3.setRoundBottomLeft(20);
        panelRound3.setRoundBottomRight(20);
        panelRound3.setRoundTopLeft(20);
        panelRound3.setRoundTopRight(20);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgLogin/buaan).jpg"))); // NOI18N
        jLabel5.setMaximumSize(new java.awt.Dimension(150, 150));
        jLabel5.setMinimumSize(new java.awt.Dimension(150, 150));
        jLabel5.setPreferredSize(new java.awt.Dimension(150, 150));

        buttonBuaAn.setText("Bữa ăn");
        buttonBuaAn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonBuaAn.setRadius(20);
        buttonBuaAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuaAnActionPerformed(evt);
            }
        });

        jLabelBuaAn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabelBuaAn.setText("200.000 VND");

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonBuaAn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabelBuaAn)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelBuaAn)
                .addGap(16, 16, 16))
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(buttonBuaAn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRound4.setBackground(new java.awt.Color(254, 249, 239));
        panelRound4.setPreferredSize(new java.awt.Dimension(300, 200));
        panelRound4.setRoundBottomLeft(20);
        panelRound4.setRoundBottomRight(20);
        panelRound4.setRoundTopLeft(20);
        panelRound4.setRoundTopRight(20);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgLogin/baothuc1.jpg"))); // NOI18N

        buttonBaoThuc.setText("Báo thức");
        buttonBaoThuc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonBaoThuc.setRadius(20);
        buttonBaoThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBaoThucActionPerformed(evt);
            }
        });

        jLabelBaoThuc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabelBaoThuc.setText("Miễn phí");

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addGroup(panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonBaoThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRound4Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabelBaoThuc)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelBaoThuc)
                .addGap(16, 16, 16))
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(buttonBaoThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRound5.setBackground(new java.awt.Color(254, 249, 239));
        panelRound5.setPreferredSize(new java.awt.Dimension(300, 200));
        panelRound5.setRoundBottomLeft(20);
        panelRound5.setRoundBottomRight(20);
        panelRound5.setRoundTopLeft(20);
        panelRound5.setRoundTopRight(20);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgLogin/kethem.jpg"))); // NOI18N
        jLabel9.setMaximumSize(new java.awt.Dimension(150, 150));
        jLabel9.setMinimumSize(new java.awt.Dimension(150, 150));
        jLabel9.setPreferredSize(new java.awt.Dimension(150, 150));

        buttonKeThem.setText("Kê thêm");
        buttonKeThem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonKeThem.setRadius(20);
        buttonKeThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKeThemActionPerformed(evt);
            }
        });

        jLabelKeThem.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabelKeThem.setText("350.000 VND");

        javax.swing.GroupLayout panelRound5Layout = new javax.swing.GroupLayout(panelRound5);
        panelRound5.setLayout(panelRound5Layout);
        panelRound5Layout.setHorizontalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound5Layout.createSequentialGroup()
                .addGroup(panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound5Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabelKeThem))
                    .addGroup(panelRound5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonKeThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        panelRound5Layout.setVerticalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound5Layout.createSequentialGroup()
                .addGroup(panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound5Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRound5Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(buttonKeThem, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelKeThem)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        panelRound6.setBackground(new java.awt.Color(254, 249, 239));
        panelRound6.setPreferredSize(new java.awt.Dimension(300, 200));
        panelRound6.setRoundBottomLeft(20);
        panelRound6.setRoundBottomRight(20);
        panelRound6.setRoundTopLeft(20);
        panelRound6.setRoundTopRight(20);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgLogin/giatla.jpg"))); // NOI18N

        buttonGiatLa.setText("Giặt là");
        buttonGiatLa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonGiatLa.setRadius(20);
        buttonGiatLa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGiatLaActionPerformed(evt);
            }
        });

        jLabelGiatLa.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabelGiatLa.setText("150.000 VND");

        javax.swing.GroupLayout panelRound6Layout = new javax.swing.GroupLayout(panelRound6);
        panelRound6.setLayout(panelRound6Layout);
        panelRound6Layout.setHorizontalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound6Layout.createSequentialGroup()
                .addGroup(panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound6Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonGiatLa, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRound6Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabelGiatLa)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        panelRound6Layout.setVerticalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound6Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelGiatLa)
                .addGap(16, 16, 16))
            .addGroup(panelRound6Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(buttonGiatLa, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRound7.setBackground(new java.awt.Color(254, 249, 239));
        panelRound7.setPreferredSize(new java.awt.Dimension(300, 200));
        panelRound7.setRoundBottomLeft(20);
        panelRound7.setRoundBottomRight(20);
        panelRound7.setRoundTopLeft(20);
        panelRound7.setRoundTopRight(20);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgLogin/duadon.jpg"))); // NOI18N

        buttonDuaDon.setText("Đưa đón");
        buttonDuaDon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonDuaDon.setRadius(20);
        buttonDuaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDuaDonActionPerformed(evt);
            }
        });

        jLabelDuaDon.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabelDuaDon.setText("200.000 VND");

        javax.swing.GroupLayout panelRound7Layout = new javax.swing.GroupLayout(panelRound7);
        panelRound7.setLayout(panelRound7Layout);
        panelRound7Layout.setHorizontalGroup(
            panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound7Layout.createSequentialGroup()
                .addGroup(panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound7Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonDuaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRound7Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabelDuaDon)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        panelRound7Layout.setVerticalGroup(
            panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDuaDon)
                .addGap(16, 16, 16))
            .addGroup(panelRound7Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(buttonDuaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(panelRound4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addComponent(panelRound5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(panelRound6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(panelRound7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRound4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRound7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelRound6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelRound5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        scrollPaneWin111.setViewportView(panelRound1);

        tableDV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên dịch vụ", "Số lượng", "Phòng", "Giá", "Chỉnh sửa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableDV.setRowHeight(40);
        jScrollPane1.setViewportView(tableDV);
        if (tableDV.getColumnModel().getColumnCount() > 0) {
            tableDV.getColumnModel().getColumn(0).setMinWidth(100);
            tableDV.getColumnModel().getColumn(0).setPreferredWidth(100);
            tableDV.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setText("Dịch vụ ");

        button7.setBorder(null);
        button7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgLogin/search.png"))); // NOI18N
        button7.setBorderColor(new java.awt.Color(255, 255, 255));
        button7.setRadius(20);

        button1.setBackground(new java.awt.Color(255, 203, 119));
        button1.setBorder(null);
        button1.setText("Đặt");
        button1.setBorderColor(new java.awt.Color(255, 255, 255));
        button1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        button1.setRadius(20);

        giaDV.setText("0 VND");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(giaDV, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrollPaneWin111, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(119, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textFieldShadow1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(100, 100, 100)
                    .addComponent(jLabel2)
                    .addContainerGap(1124, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldShadow1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollPaneWin111, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(giaDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jButton1))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(725, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 1300, -1));
        jPanel1.add(menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 78, 240, 790));
        jPanel1.add(header1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 80));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private int quantity = 0;
    private int counter = 1;
    private void buttonRuouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRuouActionPerformed
        // TODO add your handling code here:
                  // Lấy nội dung của nút buttonRuou
    String productName = buttonRuou.getText();

    // Lấy giá từ jLabelRuou và loại bỏ ký hiệu tiền tệ "VND", dấu phẩy và chuyển đổi sang số
    String priceString = jLabelRuou.getText().replace(".", "").replace(",", "").replace(" VND", "");
    double price = Double.parseDouble(priceString);

    boolean found = false;
    int rowCount = tableDV.getRowCount();
    for (int i = 0; i < rowCount; i++) {
        String existingProductName = (String) tableDV.getValueAt(i, 1);
        if (productName.equals(existingProductName)) {
            // Tăng số lượng và cập nhật giá mới cho hàng đã có trong bảng
            int quantity = (int) tableDV.getValueAt(i, 2);
            double totalPrice = Double.parseDouble(tableDV.getValueAt(i, 4).toString().replace(".", "").replace(",", "").replace(" VND", ""));
            quantity++;
            totalPrice += price;
            tableDV.setValueAt(quantity, i, 2);
            tableDV.setValueAt(String.format("%,.0f VND", totalPrice), i, 4);
            found = true;
            break;
        }
    }

    if (!found) {
        // Thêm hàng mới vào cuối bảng với số thứ tự được phát sinh
        Object[] rowData = new Object[] {counter++, productName, 1, null, String.format("%,.0f VND", price), null}; // Cột 1, 4 chưa có dữ liệu
        DefaultTableModel model = (DefaultTableModel) tableDV.getModel();
        model.addRow(rowData);
    }
    calculateTotalPrice();
    }//GEN-LAST:event_buttonRuouActionPerformed

    private void buttonBuaAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuaAnActionPerformed
        // TODO add your handling code here:
            // Lấy nội dung của nút buttonRuou
    String productName = buttonBuaAn.getText();

    // Lấy giá từ jLabelRuou và loại bỏ ký hiệu tiền tệ "VND", dấu phẩy và chuyển đổi sang số
    String priceString = jLabelBuaAn.getText().replace(".", "").replace(",", "").replace(" VND", "");
    double price = Double.parseDouble(priceString);

    boolean found = false;
    int rowCount = tableDV.getRowCount();
    for (int i = 0; i < rowCount; i++) {
        String existingProductName = (String) tableDV.getValueAt(i, 1);
        if (productName.equals(existingProductName)) {
            // Tăng số lượng và cập nhật giá mới cho hàng đã có trong bảng
            int quantity = (int) tableDV.getValueAt(i, 2);
            double totalPrice = Double.parseDouble(tableDV.getValueAt(i, 4).toString().replace(".", "").replace(",", "").replace(" VND", ""));
            quantity++;
            totalPrice += price;
            tableDV.setValueAt(quantity, i, 2);
            tableDV.setValueAt(String.format("%,.0f VND", totalPrice), i, 4);
            found = true;
            break;
        }
    }

    if (!found) {
        // Thêm hàng mới vào cuối bảng với số thứ tự được phát sinh
        Object[] rowData = new Object[] {counter++, productName, 1, null, String.format("%,.0f VND", price), null}; // Cột 1, 4 chưa có dữ liệu
        DefaultTableModel model = (DefaultTableModel) tableDV.getModel();
        model.addRow(rowData);
    }
    calculateTotalPrice();
    }//GEN-LAST:event_buttonBuaAnActionPerformed

    private void buttonBaoThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBaoThucActionPerformed
        // TODO add your handling code here:
            // Lấy nội dung của nút buttonRuou
    String productName = buttonBaoThuc.getText();

    // Lấy giá từ jLabelRuou và loại bỏ ký hiệu tiền tệ "VND", dấu phẩy và chuyển đổi sang số
    String price = jLabelBaoThuc.getText();

    boolean found = false;
    int rowCount = tableDV.getRowCount();
    for (int i = 0; i < rowCount; i++) {
        String existingProductName = (String) tableDV.getValueAt(i, 1);
        if (productName.equals(existingProductName)) {
            // Tăng số lượng và cập nhật giá mới cho hàng đã có trong bảng
            int quantity = (int) tableDV.getValueAt(i, 2);
            quantity++;
            tableDV.setValueAt(quantity, i, 2);
            tableDV.setValueAt(price, i, 4);
            found = true;
            break;
        }
    }

    if (!found) {
        // Thêm hàng mới vào cuối bảng với số thứ tự được phát sinh
        Object[] rowData = new Object[] {counter++, productName, 1, null,price, null}; // Cột 1, 4 chưa có dữ liệu
        DefaultTableModel model = (DefaultTableModel) tableDV.getModel();
        model.addRow(rowData);
    }
    }//GEN-LAST:event_buttonBaoThucActionPerformed

    private void buttonKeThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKeThemActionPerformed
        // TODO add your handling code here:
        // Lấy nội dung của nút buttonRuou
    String productName = buttonKeThem.getText();

    // Lấy giá từ jLabelRuou và loại bỏ ký hiệu tiền tệ "VND", dấu phẩy và chuyển đổi sang số
    String priceString = jLabelKeThem.getText().replace(".", "").replace(",", "").replace(" VND", "");
    double price = Double.parseDouble(priceString);

    boolean found = false;
    int rowCount = tableDV.getRowCount();
    for (int i = 0; i < rowCount; i++) {
        String existingProductName = (String) tableDV.getValueAt(i, 1);
        if (productName.equals(existingProductName)) {
            // Tăng số lượng và cập nhật giá mới cho hàng đã có trong bảng
            int quantity = (int) tableDV.getValueAt(i, 2);
            double totalPrice = Double.parseDouble(tableDV.getValueAt(i, 4).toString().replace(".", "").replace(",", "").replace(" VND", ""));
            quantity++;
            totalPrice += price;
            tableDV.setValueAt(quantity, i, 2);
            tableDV.setValueAt(String.format("%,.0f VND", totalPrice), i, 4);
            found = true;
            break;
        }
    }

    if (!found) {
        // Thêm hàng mới vào cuối bảng với số thứ tự được phát sinh
        Object[] rowData = new Object[] {counter++, productName, 1, null, String.format("%,.0f VND", price), null}; // Cột 1, 4 chưa có dữ liệu
        DefaultTableModel model = (DefaultTableModel) tableDV.getModel();
        model.addRow(rowData);
    }
    calculateTotalPrice();
    }//GEN-LAST:event_buttonKeThemActionPerformed

    private void buttonGiatLaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGiatLaActionPerformed
        // TODO add your handling code here:
        // Lấy nội dung của nút buttonRuou
    String productName = buttonGiatLa.getText();

    // Lấy giá từ jLabelRuou và loại bỏ ký hiệu tiền tệ "VND", dấu phẩy và chuyển đổi sang số
    String priceString = jLabelGiatLa.getText().replace(".", "").replace(",", "").replace(" VND", "");
    double price = Double.parseDouble(priceString);

    boolean found = false;
    int rowCount = tableDV.getRowCount();
    for (int i = 0; i < rowCount; i++) {
        String existingProductName = (String) tableDV.getValueAt(i, 1);
        if (productName.equals(existingProductName)) {
            // Tăng số lượng và cập nhật giá mới cho hàng đã có trong bảng
            int quantity = (int) tableDV.getValueAt(i, 2);
            double totalPrice = Double.parseDouble(tableDV.getValueAt(i, 4).toString().replace(".", "").replace(",", "").replace(" VND", ""));
            quantity++;
            totalPrice += price;
            tableDV.setValueAt(quantity, i, 2);
            tableDV.setValueAt(String.format("%,.0f VND", totalPrice), i, 4);
            found = true;
            break;
        }
    }

    if (!found) {
        // Thêm hàng mới vào cuối bảng với số thứ tự được phát sinh
        Object[] rowData = new Object[] {counter++, productName, 1, null, String.format("%,.0f VND", price), null}; // Cột 1, 4 chưa có dữ liệu
        DefaultTableModel model = (DefaultTableModel) tableDV.getModel();
        model.addRow(rowData);
    }
    calculateTotalPrice();
    }//GEN-LAST:event_buttonGiatLaActionPerformed

    private void buttonDuaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDuaDonActionPerformed
        // TODO add your handling code here:
        // Lấy nội dung của nút buttonRuou
    String productName = buttonDuaDon.getText();

    // Lấy giá từ jLabelRuou và loại bỏ ký hiệu tiền tệ "VND", dấu phẩy và chuyển đổi sang số
    String priceString = jLabelDuaDon.getText().replace(".", "").replace(",", "").replace(" VND", "");
    double price = Double.parseDouble(priceString);

    boolean found = false;
    int rowCount = tableDV.getRowCount();
    for (int i = 0; i < rowCount; i++) {
        String existingProductName = (String) tableDV.getValueAt(i, 1);
        if (productName.equals(existingProductName)) {
            // Tăng số lượng và cập nhật giá mới cho hàng đã có trong bảng
            int quantity = (int) tableDV.getValueAt(i, 2);
            double totalPrice = Double.parseDouble(tableDV.getValueAt(i, 4).toString().replace(".", "").replace(",", "").replace(" VND", ""));
            quantity++;
            totalPrice += price;
            tableDV.setValueAt(quantity, i, 2);
            tableDV.setValueAt(String.format("%,.0f VND", totalPrice), i, 4);
            found = true;
            break;
        }
    }

    if (!found) {
        // Thêm hàng mới vào cuối bảng với số thứ tự được phát sinh
        Object[] rowData = new Object[] {counter++, productName, 1, null, String.format("%,.0f VND", price), null}; // Cột 1, 4 chưa có dữ liệu
        DefaultTableModel model = (DefaultTableModel) tableDV.getModel();
        model.addRow(rowData);
    }
    calculateTotalPrice();
    }//GEN-LAST:event_buttonDuaDonActionPerformed
// Phương thức tính toán tổng giá tiền và cập nhật lên textField giaDV
private void calculateTotalPrice() {
    double total = 0;

    // Lặp qua từng hàng trong bảng
    int rowCount = tableDV.getRowCount();
    for (int i = 0; i < rowCount; i++) {
        // Lấy giá trị của cột "Giá"
        String priceString = (String) tableDV.getValueAt(i, 4);
        // Kiểm tra xem dịch vụ có phải là "Miễn phí" không
        if (!"Miễn phí".equals(priceString)) {
            // Chuyển đổi giá thành số và cộng vào tổng
            double price = Double.parseDouble(priceString.replace(".", "").replace(",", "").replace(" VND", ""));
            total += price;
        }
    }

    // Hiển thị tổng giá trong textField giaDV
    giaDV.setText(String.format("%,.0f VND", total));
}


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DichVu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private giaodien.Button button1;
    private giaodien.Button button7;
    private giaodien.Button buttonBaoThuc;
    private giaodien.Button buttonBuaAn;
    private giaodien.Button buttonDuaDon;
    private giaodien.Button buttonGiatLa;
    private giaodien.Button buttonKeThem;
    private giaodien.Button buttonRuou;
    private giaodien.TextFieldShadow giaDV;
    private component.Header header1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBaoThuc;
    private javax.swing.JLabel jLabelBuaAn;
    private javax.swing.JLabel jLabelDuaDon;
    private javax.swing.JLabel jLabelGiatLa;
    private javax.swing.JLabel jLabelKeThem;
    private javax.swing.JLabel jLabelRuou;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private menu.Menu menu1;
    private giaodien.PanelRound panelRound1;
    private giaodien.PanelRound panelRound2;
    private giaodien.PanelRound panelRound3;
    private giaodien.PanelRound panelRound4;
    private giaodien.PanelRound panelRound5;
    private giaodien.PanelRound panelRound6;
    private giaodien.PanelRound panelRound7;
    private ScollBar1.ScrollPaneWin11 scrollPaneWin111;
    private javax.swing.JTable tableDV;
    private giaodien.TextFieldShadow textFieldShadow1;
    // End of variables declaration//GEN-END:variables
}
